services:
  exoscopy:
    build: .
    container_name: exoscopy
    ports:
      - "3456:3456"
    restart: unless-stopped
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./data:/app/data
    environment:
      - NODE_ENV=production
